# Generated by Django 4.1.7 on 2023-03-01 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_comment_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='product',
            field=models.ManyToManyField(blank=True, to='goods.product'),
        ),
    ]
