# Generated by Django 4.1.7 on 2023-03-18 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_alter_property_connection_alter_property_usb_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='camera_front',
            field=models.CharField(blank=True, max_length=100, verbose_name='Front Camera'),
        ),
        migrations.AlterField(
            model_name='property',
            name='camera_main',
            field=models.CharField(blank=True, max_length=100, verbose_name='Main Camera'),
        ),
    ]
