# Generated by Django 4.1.7 on 2023-03-18 12:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0007_alter_property_camera_front_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='properties',
        ),
        migrations.RemoveField(
            model_name='property',
            name='battery_cap',
        ),
        migrations.RemoveField(
            model_name='property',
            name='bluetooth',
        ),
        migrations.RemoveField(
            model_name='property',
            name='camera_front',
        ),
        migrations.RemoveField(
            model_name='property',
            name='camera_main',
        ),
        migrations.RemoveField(
            model_name='property',
            name='charge_power',
        ),
        migrations.RemoveField(
            model_name='property',
            name='connection',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cpu',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cpu_cores',
        ),
        migrations.RemoveField(
            model_name='property',
            name='cpu_freq',
        ),
        migrations.RemoveField(
            model_name='property',
            name='dimensions',
        ),
        migrations.RemoveField(
            model_name='property',
            name='equipment',
        ),
        migrations.RemoveField(
            model_name='property',
            name='graphics_ram_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='graphics_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='hdmi',
        ),
        migrations.RemoveField(
            model_name='property',
            name='material',
        ),
        migrations.RemoveField(
            model_name='property',
            name='operation_system',
        ),
        migrations.RemoveField(
            model_name='property',
            name='quick_charge',
        ),
        migrations.RemoveField(
            model_name='property',
            name='ram_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='ram_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rom_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='rom_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='screen_diagonal',
        ),
        migrations.RemoveField(
            model_name='property',
            name='screen_resolution',
        ),
        migrations.RemoveField(
            model_name='property',
            name='screen_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='sensors',
        ),
        migrations.RemoveField(
            model_name='property',
            name='usb_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='property',
            name='wifi_type',
        ),
        migrations.RemoveField(
            model_name='property',
            name='work_time',
        ),
        migrations.AddField(
            model_name='property',
            name='name',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='value',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='property_category',
            field=models.ManyToManyField(related_name='product_properties', to='goods.propertycategory'),
        ),
        migrations.AddField(
            model_name='property',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='goods.propertycategory'),
            preserve_default=False,
        ),
    ]
