# Generated by Django 4.1.7 on 2023-03-18 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0008_propertycategory_remove_product_properties_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='propertycategory',
            options={'verbose_name': 'Property Category', 'verbose_name_plural': 'Property Categories'},
        ),
    ]
