# Generated by Django 4.1.7 on 2023-03-18 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0010_property_units'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='category',
        ),
        migrations.AddField(
            model_name='property',
            name='category_product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='goods.category'),
        ),
        migrations.AddField(
            model_name='property',
            name='category_property',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category_properties', to='goods.propertycategory'),
        ),
    ]
