# Generated by Django 4.1.7 on 2023-03-18 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_remove_property_category_property_category_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='property_category',
        ),
        migrations.RemoveField(
            model_name='property',
            name='category_product',
        ),
        migrations.AddField(
            model_name='property',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='goods.product'),
        ),
    ]
