# Generated by Django 4.1.7 on 2023-03-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_remove_product_property_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('category_property',), 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='product_categories',
            field=models.ManyToManyField(to='goods.category'),
        ),
    ]
