# Generated by Django 4.1.7 on 2023-03-22 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_alter_property_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='product_categories',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='product_categories', to='goods.category'),
        ),
    ]
