# Generated by Django 4.1.7 on 2023-03-22 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_property_product_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='product_categories',
        ),
    ]
