# Generated by Django 4.1.7 on 2023-03-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_remove_property_product_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='detail_description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
