# Generated by Django 4.1.7 on 2023-03-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_property_detail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='products_<django.db.models.fields.CharField>/%Y/%m/%d'),
        ),
    ]
