# Generated by Django 4.1.7 on 2023-03-25 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0018_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='value',
            new_name='text_value',
        ),
        migrations.AddField(
            model_name='property',
            name='numeric_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=6),
            preserve_default=False,
        ),
    ]
