# Generated by Django 4.1.7 on 2023-03-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0020_alter_property_text_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='numeric_value',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6),
        ),
    ]
