# Generated by Django 4.1.7 on 2023-03-28 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0021_alter_property_numeric_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(choices=[('Colors', 'Colors'), ('Diagonal', 'Diagonal'), ('Pixel Density', 'Pixel Density'), ('Type', 'Type'), ('Resolution', 'Resolution'), ('Brightness', 'Brightness'), ('Sweep frequency', 'Sweep frequency'), ('#Cores', '#Cores'), ('Frequency', 'Frequency'), ('Model', 'Model'), ('Threads', 'Threads'), ('Front', 'Front'), ('Main', 'Main'), ('Bluetooth', 'Bluetooth'), ('NFC', 'NFC'), ('Positioning', 'Positioning'), ('Radio', 'Radio'), ('SIM', 'SIM'), ('Speed', 'Speed'), ('USB', 'USB'), ('WI-FI', 'WI-FI'), ('Audio Port', 'Audio Port'), ('HDMI', 'HDMI'), ('LAN', 'LAN'), ('4G', '4G'), ('5G', '5G'), ('Capacity', 'Capacity'), ('Charging', 'Charging'), ('Quick Charge', 'Quick Charge'), ('#Cells', '#Cells'), ('Work Time', 'Work Time'), ('Color', 'Color'), ('Dimensions', 'Dimensions'), ('Material', 'Material'), ('Weight', 'Weight'), ('Opening Angle', 'Opening Angle'), ('Manufacturer', 'Manufacturer'), ('Power', 'Power'), ('Volume', 'Volume'), ('#Slots', '#Slots'), ('Firmware', 'Firmware'), ('Form Factor', 'Form Factor'), ('Card slot', 'Card slot'), ('Sensors', 'Sensors'), ('OS', 'OS'), ('User interface', 'User interface'), ('Version', 'Version')], max_length=50),
        ),
    ]
