# Generated by Django 4.1.7 on 2023-04-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0023_product_promotional_alter_property_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='detail_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
