# Generated by Django 4.1.7 on 2023-05-25 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_profile_photo'),
        ('goods', '0030_alter_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profiles_likes',
            field=models.ManyToManyField(blank=True, default=0, related_name='comments_liked', to='account.profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='profiles_unlikes',
            field=models.ManyToManyField(blank=True, default=0, related_name='comments_unliked', to='account.profile'),
        ),
    ]
