# Generated by Django 4.1.7 on 2023-06-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0031_comment_profiles_likes_comment_profiles_unlikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='detail_description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
