# Generated by Django 4.1.7 on 2023-06-12 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0032_alter_property_detail_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='detail_description',
            field=models.TextField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(choices=[('#Cells', '#Cells'), ('#Cores', '#Cores'), ('#Slots', '#Slots'), ('4G', '4G'), ('5G', '5G'), ('Additional Features', 'Additional Features'), ('Audio Port', 'Audio Port'), ('Bluetooth', 'Bluetooth'), ('Brightness', 'Brightness'), ('Capacity', 'Capacity'), ('Card slot', 'Card slot'), ('Charging', 'Charging'), ('Color', 'Color'), ('Colors', 'Colors'), ('Diagonal', 'Diagonal'), ('Dimensions', 'Dimensions'), ('Firmware', 'Firmware'), ('Form Factor', 'Form Factor'), ('Frequency', 'Frequency'), ('Front', 'Front'), ('HDMI', 'HDMI'), ('Keyboard Lightening', 'Keyboard Lightening'), ('LAN', 'LAN'), ('Main', 'Main'), ('Manufacturer', 'Manufacturer'), ('Material', 'Material'), ('Model', 'Model'), ('NFC', 'NFC'), ('OS', 'OS'), ('Opening Angle', 'Opening Angle'), ('Packaging', 'Packaging'), ('Pixel Density', 'Pixel Density'), ('Positioning', 'Positioning'), ('Power', 'Power'), ('Quick Charge', 'Quick Charge'), ('Radio', 'Radio'), ('Resolution', 'Resolution'), ('SIM', 'SIM'), ('Sensors', 'Sensors'), ('Speed', 'Speed'), ('Sweep frequency', 'Sweep frequency'), ('Threads', 'Threads'), ('Type', 'Type'), ('USB', 'USB'), ('User interface', 'User interface'), ('Version', 'Version'), ('Volume', 'Volume'), ('WI-FI', 'WI-FI'), ('Weight', 'Weight'), ('Work Time', 'Work Time')], max_length=50),
        ),
    ]
