# Generated by Django 4.1.7 on 2023-06-13 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0034_alter_property_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(choices=[('#Cells', '#Cells'), ('#Cores', '#Cores'), ('#Slots', '#Slots'), ('4G', '4G'), ('5G', '5G'), ('Additional Features', 'Additional Features'), ('Audio Port', 'Audio Port'), ('Bluetooth', 'Bluetooth'), ('Brightness', 'Brightness'), ('Capacity', 'Capacity'), ('Card slot', 'Card slot'), ('Channels', 'Channels'), ('Charging', 'Charging'), ('Charging Port', 'Charging Port'), ('Color', 'Color'), ('Colors', 'Colors'), ('Connections', 'Connections'), ('Diagonal', 'Diagonal'), ('Dimensions', 'Dimensions'), ('Firmware', 'Firmware'), ('Form Factor', 'Form Factor'), ('Frequency', 'Frequency'), ('Frequency Range', 'Frequency Range'), ('Front', 'Front'), ('HDMI', 'HDMI'), ('Inputs', 'Inputs'), ('Interfaces', 'Interfaces'), ('Keyboard Lightening', 'Keyboard Lightening'), ('LAN', 'LAN'), ('Main', 'Main'), ('Manufacturer', 'Manufacturer'), ('Material', 'Material'), ('Model', 'Model'), ('NFC', 'NFC'), ('OS', 'OS'), ('Opening Angle', 'Opening Angle'), ('Packaging', 'Packaging'), ('Pixel Density', 'Pixel Density'), ('Positioning', 'Positioning'), ('Power', 'Power'), ('Quick Charge', 'Quick Charge'), ('Radio', 'Radio'), ('Resolution', 'Resolution'), ('SIM', 'SIM'), ('Sensors', 'Sensors'), ('Speed', 'Speed'), ('Supply Types', 'Supply Types'), ('Sweep frequency', 'Sweep frequency'), ('Threads', 'Threads'), ('Type', 'Type'), ('USB', 'USB'), ('User interface', 'User interface'), ('Version', 'Version'), ('Volume', 'Volume'), ('WI-FI', 'WI-FI'), ('Weight', 'Weight'), ('Work Time', 'Work Time')], max_length=50),
        ),
    ]
