# Generated by Django 4.1.7 on 2023-09-08 11:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0035_alter_property_name'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('available_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
