# Generated by Django 4.1.7 on 2023-10-21 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0038_alter_category_options_alter_favorite_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='category_property',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='category_properties', to='goods.propertycategory', verbose_name='Category property'),
        ),
        migrations.AlterField(
            model_name='property',
            name='detail_description',
            field=models.TextField(blank=True, max_length=600, verbose_name='Detail description'),
        ),
        migrations.AlterField(
            model_name='property',
            name='name',
            field=models.CharField(choices=[('#Cells', '#Cells'), ('#Cores', '#Cores'), ('#Slots', '#Slots'), ('4G', '4G'), ('5G', '5G'), ('Additional Features', 'Additional Features'), ('Audio Port', 'Audio Port'), ('Bluetooth', 'Bluetooth'), ('Brightness', 'Brightness'), ('Capacity', 'Capacity'), ('Card slot', 'Card slot'), ('Channels', 'Channels'), ('Charging', 'Charging'), ('Charging Port', 'Charging Port'), ('Color', 'Color'), ('Colors', 'Colors'), ('Connections', 'Connections'), ('Diagonal', 'Diagonal'), ('Dimensions', 'Dimensions'), ('FOV', 'FOV'), ('Firmware', 'Firmware'), ('Form Factor', 'Form Factor'), ('Frequency', 'Frequency'), ('Frequency Range', 'Frequency Range'), ('Front', 'Front'), ('HDMI', 'HDMI'), ('Image sensor', 'Image sensor'), ('Inputs', 'Inputs'), ('Interfaces', 'Interfaces'), ('Keyboard Lightening', 'Keyboard Lightening'), ('LAN', 'LAN'), ('Main', 'Main'), ('Manufacturer', 'Manufacturer'), ('Material', 'Material'), ('Model', 'Model'), ('NFC', 'NFC'), ('OS', 'OS'), ('Opening Angle', 'Opening Angle'), ('Packaging', 'Packaging'), ('Pixel Density', 'Pixel Density'), ('Positioning', 'Positioning'), ('Power', 'Power'), ('Quick Charge', 'Quick Charge'), ('Radio', 'Radio'), ('Resolution', 'Resolution'), ('SIM', 'SIM'), ('Sensors', 'Sensors'), ('Speed', 'Speed'), ('Supply Types', 'Supply Types'), ('Sweep frequency', 'Sweep frequency'), ('Threads', 'Threads'), ('Type', 'Type'), ('USB', 'USB'), ('User interface', 'User interface'), ('Version', 'Version'), ('Volume', 'Volume'), ('WI-FI', 'WI-FI'), ('Weight', 'Weight'), ('Work Time', 'Work Time')], default='', max_length=50, verbose_name='Property name'),
        ),
        migrations.AlterField(
            model_name='property',
            name='numeric_value',
            field=models.DecimalField(blank=True, decimal_places=2, default='0.00', max_digits=6, verbose_name='Numeric value'),
        ),
        migrations.AlterField(
            model_name='property',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='goods.product', verbose_name='Product'),
        ),
        migrations.AlterField(
            model_name='property',
            name='text_value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Text value'),
        ),
        migrations.AlterField(
            model_name='property',
            name='units',
            field=models.CharField(blank=True, max_length=10, verbose_name='Units'),
        ),
    ]
