# Generated by Django 4.1.7 on 2023-10-21 14:40

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0040_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
        migrations.RemoveField(
            model_name='property',
            name='name',
        ),
        migrations.AddField(
            model_name='property',
            name='name_old',
            field=models.CharField(choices=[('#Cells', '#Cells'), ('#Cores', '#Cores'), ('#Slots', '#Slots'), ('4G', '4G'), ('5G', '5G'), ('Additional Features', 'Additional Features'), ('Audio Port', 'Audio Port'), ('Bluetooth', 'Bluetooth'), ('Brightness', 'Brightness'), ('Capacity', 'Capacity'), ('Card slot', 'Card slot'), ('Channels', 'Channels'), ('Charging', 'Charging'), ('Charging Port', 'Charging Port'), ('Color', 'Color'), ('Colors', 'Colors'), ('Connections', 'Connections'), ('Diagonal', 'Diagonal'), ('Dimensions', 'Dimensions'), ('FOV', 'FOV'), ('Firmware', 'Firmware'), ('Form Factor', 'Form Factor'), ('Frequency', 'Frequency'), ('Frequency Range', 'Frequency Range'), ('Front', 'Front'), ('HDMI', 'HDMI'), ('Image sensor', 'Image sensor'), ('Inputs', 'Inputs'), ('Interfaces', 'Interfaces'), ('Keyboard Lightening', 'Keyboard Lightening'), ('LAN', 'LAN'), ('Main', 'Main'), ('Manufacturer', 'Manufacturer'), ('Material', 'Material'), ('Model', 'Model'), ('NFC', 'NFC'), ('OS', 'OS'), ('Opening Angle', 'Opening Angle'), ('Packaging', 'Packaging'), ('Pixel Density', 'Pixel Density'), ('Positioning', 'Positioning'), ('Power', 'Power'), ('Quick Charge', 'Quick Charge'), ('Radio', 'Radio'), ('Resolution', 'Resolution'), ('SIM', 'SIM'), ('Sensors', 'Sensors'), ('Speed', 'Speed'), ('Supply Types', 'Supply Types'), ('Sweep frequency', 'Sweep frequency'), ('Threads', 'Threads'), ('Type', 'Type'), ('USB', 'USB'), ('User interface', 'User interface'), ('Version', 'Version'), ('Volume', 'Volume'), ('WI-FI', 'WI-FI'), ('Weight', 'Weight'), ('Work Time', 'Work Time')], default='', max_length=50, verbose_name='Property name'),
        ),
        migrations.CreateModel(
            name='PropertyTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(choices=[('#Cells', '#Cells'), ('#Cores', '#Cores'), ('#Slots', '#Slots'), ('4G', '4G'), ('5G', '5G'), ('Additional Features', 'Additional Features'), ('Audio Port', 'Audio Port'), ('Bluetooth', 'Bluetooth'), ('Brightness', 'Brightness'), ('Capacity', 'Capacity'), ('Card slot', 'Card slot'), ('Channels', 'Channels'), ('Charging', 'Charging'), ('Charging Port', 'Charging Port'), ('Color', 'Color'), ('Colors', 'Colors'), ('Connections', 'Connections'), ('Diagonal', 'Diagonal'), ('Dimensions', 'Dimensions'), ('FOV', 'FOV'), ('Firmware', 'Firmware'), ('Form Factor', 'Form Factor'), ('Frequency', 'Frequency'), ('Frequency Range', 'Frequency Range'), ('Front', 'Front'), ('HDMI', 'HDMI'), ('Image sensor', 'Image sensor'), ('Inputs', 'Inputs'), ('Interfaces', 'Interfaces'), ('Keyboard Lightening', 'Keyboard Lightening'), ('LAN', 'LAN'), ('Main', 'Main'), ('Manufacturer', 'Manufacturer'), ('Material', 'Material'), ('Model', 'Model'), ('NFC', 'NFC'), ('OS', 'OS'), ('Opening Angle', 'Opening Angle'), ('Packaging', 'Packaging'), ('Pixel Density', 'Pixel Density'), ('Positioning', 'Positioning'), ('Power', 'Power'), ('Quick Charge', 'Quick Charge'), ('Radio', 'Radio'), ('Resolution', 'Resolution'), ('SIM', 'SIM'), ('Sensors', 'Sensors'), ('Speed', 'Speed'), ('Supply Types', 'Supply Types'), ('Sweep frequency', 'Sweep frequency'), ('Threads', 'Threads'), ('Type', 'Type'), ('USB', 'USB'), ('User interface', 'User interface'), ('Version', 'Version'), ('Volume', 'Volume'), ('WI-FI', 'WI-FI'), ('Weight', 'Weight'), ('Work Time', 'Work Time')], default='', max_length=50, verbose_name='Property name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='goods.property')),
            ],
            options={
                'verbose_name': 'Property Translation',
                'db_table': 'goods_property_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
