# Generated by Django 4.1.7 on 2023-10-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0042_migrate_translatable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='name_old',
        ),
    ]
