# Generated by Django 4.1.7 on 2023-10-21 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0043_remove_untranslated_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ('category_property',), 'verbose_name': 'Property', 'verbose_name_plural': 'Properties'},
        ),
    ]
