# Generated by Django 4.1.9 on 2023-10-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0044_alter_property_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='detail_description',
        ),
        migrations.RemoveField(
            model_name='property',
            name='text_value',
        ),
        migrations.RemoveField(
            model_name='property',
            name='units',
        ),
        migrations.AddField(
            model_name='property',
            name='detail_description_old',
            field=models.TextField(blank=True, max_length=600, verbose_name='Detail description'),
        ),
        migrations.AddField(
            model_name='property',
            name='text_value_old',
            field=models.CharField(blank=True, max_length=255, verbose_name='Text value'),
        ),
        migrations.AddField(
            model_name='property',
            name='units_old',
            field=models.CharField(blank=True, max_length=10, verbose_name='Units'),
        ),
        migrations.AddField(
            model_name='propertytranslation',
            name='detail_description',
            field=models.TextField(blank=True, max_length=600, verbose_name='Detail description'),
        ),
        migrations.AddField(
            model_name='propertytranslation',
            name='text_value',
            field=models.CharField(blank=True, max_length=255, verbose_name='Text value'),
        ),
        migrations.AddField(
            model_name='propertytranslation',
            name='units',
            field=models.CharField(blank=True, max_length=10, verbose_name='Units'),
        ),
    ]
