# Generated by Django 4.1.9 on 2023-10-22 10:55

from django.db import migrations
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist


def forwards_func(apps, schema_editor):
    MyModel = apps.get_model('goods', 'Property')
    MyModelTranslation = apps.get_model('goods', 'PropertyTranslation')

    for object in MyModel.objects.all():
        MyModelTranslation.objects.create(
            master_id=object.pk,
            language_code=settings.LANGUAGE_CODE,
            text_value=object.text_value_old,
            units=object.units_old,
            detail_description=object.detail_description_old,
        )

def backwards_func(apps, schema_editor):
    MyModel = apps.get_model('myapp', 'Property')
    MyModelTranslation = apps.get_model('goods', 'PropertyTranslation')

    for object in MyModel.objects.all():
        translation = _get_translation(object, MyModelTranslation)
        object.text_value = translation.text_value
        object.units = translation.units
        object.detail_description = translation.detail_description
        object.save()   # Note this only calls Model.save()

def _get_translation(object, MyModelTranslation):
    translations = MyModelTranslation.objects.filter(master_id=object.pk)
    try:
        # Try default translation
        return translations.get(language_code=settings.LANGUAGE_CODE)
    except ObjectDoesNotExist:
        try:
            # Try default language
            return translations.get(language_code=settings.PARLER_DEFAULT_LANGUAGE_CODE)
        except ObjectDoesNotExist:
            # Maybe the object was translated only in a specific language?
            # Hope there is a single translation
            return translations.get()


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0045_add_translation_model_prop'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
