# Generated by Django 4.1.9 on 2023-10-22 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0046_migrate_translatable_fields_prop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='detail_description_old',
        ),
        migrations.RemoveField(
            model_name='property',
            name='text_value_old',
        ),
        migrations.RemoveField(
            model_name='property',
            name='units_old',
        ),
    ]
