# Generated by Django 4.1.9 on 2023-10-22 12:34

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0047_remove_untranslated_fields_prop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertycategory',
            name='name',
        ),
        migrations.AddField(
            model_name='propertycategory',
            name='name_old',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
        migrations.CreateModel(
            name='PropertyCategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(default='', max_length=100, verbose_name='Name')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='goods.propertycategory')),
            ],
            options={
                'verbose_name': 'Property Category Translation',
                'db_table': 'goods_propertycategory_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
