# Generated by Django 4.1.9 on 2023-10-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0049_migrate_translatable_fields_category_prop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertycategory',
            name='name_old',
        ),
    ]
