# Generated by Django 4.1.7 on 2023-05-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_category_options_coupon_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='active',
        ),
    ]
