# Generated by Django 4.1.7 on 2023-10-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_remove_coupon_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='coupon',
            options={'ordering': ('id',)},
        ),
    ]
