# Generated by Django 4.1.7 on 2023-03-07 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_category_options_coupon_category'),
        ('present_cards', '0003_alter_category_options'),
        ('account', '0003_profile_about_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='coupons',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_coupons', to='coupons.coupon'),
        ),
        migrations.AddField(
            model_name='profile',
            name='present_cart',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_present_cards', to='present_cards.presentcard'),
        ),
    ]
