# Generated by Django 4.1.7 on 2023-03-07 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_category_options_coupon_category'),
        ('account', '0005_remove_profile_coupons_profile_coupons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coupons',
            field=models.ManyToManyField(related_name='profile_coupons', to='coupons.coupon'),
        ),
    ]
