# Generated by Django 4.1.7 on 2023-03-07 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_profile_coupons'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='present_cart',
            new_name='present_card',
        ),
    ]
