# Generated by Django 4.1.7 on 2023-03-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('present_cards', '0003_alter_category_options'),
        ('account', '0007_rename_present_cart_profile_present_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='present_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_present_cards', to='present_cards.presentcard'),
        ),
    ]
