# Generated by Django 4.1.7 on 2023-03-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0002_alter_category_options_coupon_category'),
        ('account', '0008_alter_profile_present_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='coupons',
            field=models.ManyToManyField(blank=True, related_name='profile_coupons', to='coupons.coupon'),
        ),
    ]
