# Generated by Django 4.1.7 on 2023-03-08 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_profile_coupons'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='present_card',
        ),
    ]
