# Generated by Django 4.1.7 on 2023-04-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_profile_present_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirm',
            field=models.BooleanField(default=False),
        ),
    ]
