# Generated by Django 4.1.7 on 2023-04-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, max_length=500, upload_to='users/%Y/%m/%d/'),
        ),
    ]
