pipeline {
    agent any

environment {
        ENV_FILE = credentials("ENV_FILE")
        DATABASE_USER = credentials("DATABASE_USER")
}
    stages {
        stage("Clone repository to workspace") {
            steps {
                script {
                    //if project directory does not exist, clone repository and copy file with environment variables to the project
                    if (!fileExists("OnlineShop"))
                        sh '''
                            git clone https://github.com/sergey-vernyk/OnlineShop.git
                            cat ${ENV_FILE} > env && \
                            mv env ${WORKSPACE}/OnlineShop/internet_shop/int_shop/int_shop/settings/.env
                        '''
                }
            }
        }
        stage("Build and Run Containers") {
            steps {
                // build django app to image
                script {
                    def dockerfileDir = "${WORKSPACE}/OnlineShop/internet_shop/int_shop"
                    def dockerImageName = "django_web_jenkins"
                    sh "docker build -t ${dockerImageName} -f ${dockerfileDir}/Dockerfile ${dockerfileDir}"
                }
                // run built django app
                sh '''
                    cat ${ENV_FILE} > env && \
                    docker run -d --name django_app \
                        --expose 5000 \
                        -v ${WORKSPACE}/socket:/var/run/postgresql \
                        --env-file env \
                        --entrypoint /bin/sh django_web_jenkins -c "python manage.py runserver 5000"
                '''
                // run postgres container with environment variables
                sh '''
                    cat ${ENV_FILE} > env && \
                    docker run -d --name postgres_jenkins \
                        -v ${WORKSPACE}/socket:/var/run/postgresql \
                        --env-file env \
                        --expose 5432 postgres:14.6-alpine
                '''
                // run redis container
                sh '''
                    docker run -d --name redis_db_jenkins \
                        -v ${WORKSPACE}/OnlineShop/internet_shop/int_shop/config/redis/redis.conf:/usr/local/etc/redis/redis.conf \
                        --expose 6379 redis:7-alpine3.16 redis-server /usr/local/etc/redis/redis.conf
                '''
            }
        }
        stage("Create docker network and tie running containers with created network") {
            steps {
                //create docker network
                sh "docker network create jenkins-network"

                //tie all running containers to the network
                sh "docker network connect --alias redis-db jenkins-network redis_db_jenkins"
                sh "docker network connect --alias postgresql-db jenkins-network postgres_jenkins"
                sh "docker network connect --alias web_app_django jenkins-network django_app"
            }
        }
        stage("Test and Coverage") {
            steps {
                //make project's directory available for all users
                sh 'docker exec -u root django_app sh -c "cd / && chmod 777 -R /code/ && exit"'
                //make tests and coverage
                //`sleep` neccessary for waiting postgres db to connect to socket
                // create user in db for perform tests
                sh '''
                    sleep 5
                    docker exec -u root postgres_jenkins sh -c "psql -U postgres -p 5432 -c 'CREATE USER ${DATABASE_USER} CREATEDB;'"
                    docker exec django_app \
                        sh -c "coverage run --source '.' --omit '*/migrations/*,*/tests/*,*/settings/*,int_shop/*' \
                        manage.py test --exclude-tag social_profiles && \
                        coverage report && \
                        exit"
                '''
            }
        }
    }
    post { 
        success {
            //remove all containers, network and all files from workspace
            sh "docker stop redis_db_jenkins postgres_jenkins django_app"
            sh "docker rm redis_db_jenkins postgres_jenkins django_app"
            sh "docker network rm jenkins-network"
            
            sh "cd ${WORKSPACE} && rm -r OnlineShop socket env"
        }
    }
}