# Generated by Django 4.1.7 on 2023-03-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='PresentCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField()),
                ('active', models.BooleanField(default=False)),
                ('from_name', models.CharField(max_length=50)),
                ('from_email', models.EmailField(max_length=254)),
                ('to_name', models.CharField(max_length=50)),
                ('to_email', models.EmailField(max_length=254)),
                ('message', models.TextField(max_length=300)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_cards', to='present_cards.category')),
            ],
            options={
                'ordering': ('active',),
            },
        ),
    ]
