# Generated by Django 4.1.7 on 2023-03-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentcard',
            name='message',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
