# Generated by Django 4.1.7 on 2023-03-02 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('present_cards', '0002_alter_presentcard_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
