# Generated by Django 4.1.7 on 2023-03-08 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_profile_present_card'),
        ('present_cards', '0004_presentcard_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentcard',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_cards', to='account.profile'),
        ),
    ]
