# Generated by Django 4.1.7 on 2023-05-31 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('present_cards', '0007_alter_presentcard_options_remove_presentcard_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentcard',
            name='amount',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
