# Generated by Django 4.1.7 on 2023-10-21 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('present_cards', '0008_alter_presentcard_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('id',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='presentcard',
            options={'ordering': ('id',)},
        ),
    ]
