# Generated by Django 4.1.9 on 2023-10-26 12:55

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_create_translatable_fields'),
        ('present_cards', '0009_alter_category_options_alter_presentcard_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.AlterField(
            model_name='presentcard',
            name='amount',
            field=models.PositiveSmallIntegerField(verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='presentcard',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='present_cards', to='present_cards.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='presentcard',
            name='code',
            field=models.CharField(max_length=50, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='presentcard',
            name='from_email',
            field=models.EmailField(max_length=254, verbose_name='From email'),
        ),
        migrations.AlterField(
            model_name='presentcard',
            name='from_name',
            field=models.CharField(max_length=50, verbose_name='From name'),
        ),
        migrations.AlterField(
            model_name='presentcard',
            name='message',
            field=models.TextField(blank=True, max_length=300, verbose_name='Message'),
        ),
        migrations.AlterField(
            model_name='presentcard',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_cards', to='account.profile', verbose_name='Profile'),
        ),
        migrations.AlterField(
            model_name='presentcard',
            name='to_email',
            field=models.EmailField(max_length=254, verbose_name='To email'),
        ),
        migrations.AlterField(
            model_name='presentcard',
            name='to_name',
            field=models.CharField(max_length=50, verbose_name='To name'),
        ),
        migrations.AlterField(
            model_name='presentcard',
            name='valid_from',
            field=models.DateTimeField(verbose_name='Valid from'),
        ),
        migrations.AlterField(
            model_name='presentcard',
            name='valid_to',
            field=models.DateTimeField(verbose_name='Valid to'),
        ),
        migrations.CreateModel(
            name='CategoryTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='present_cards.category')),
            ],
            options={
                'verbose_name': 'Category Translation',
                'db_table': 'present_cards_category_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatableModel, models.Model),
        ),
    ]
