# Generated by Django 4.1.7 on 2023-03-02 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('present_cards', '0001_initial'),
        ('goods', '0003_alter_favorite_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('method', models.CharField(choices=[('Self-delivery', 'Self-delivery'), ('Post office', 'Post office'), ('Apartment', 'Apartment')], max_length=20)),
                ('office_number', models.IntegerField(blank=True)),
                ('delivery_date', models.DateField()),
            ],
            options={
                'ordering': ('delivery_date',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('recipient', models.CharField(blank=True, max_length=100)),
                ('comment', models.TextField(max_length=100)),
                ('call_confirm', models.BooleanField(default=False)),
                ('pay_method', models.CharField(choices=[('Online', 'Online'), ('On delivery', 'On delivery'), ('Installments', 'Installments')], max_length=20)),
                ('coupon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='coupons.coupon')),
                ('present_card', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='present_cards.presentcard')),
            ],
            options={
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='goods.product')),
            ],
        ),
    ]
