# Generated by Django 4.1.7 on 2023-03-03 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_delivery_options_alter_order_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='office_number',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
