# Generated by Django 4.1.7 on 2023-03-08 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_delivery_office_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='office_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
