# Generated by Django 4.1.7 on 2023-03-12 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_email_was_sent',
            field=models.BooleanField(default=False),
        ),
    ]
