# Generated by Django 4.1.7 on 2023-04-18 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
