# Generated by Django 4.1.7 on 2023-05-12 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_remove_order_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='service',
            field=models.CharField(blank=True, choices=[('New Post', 'New Post'), ('Ukrpost', 'Ukrpost'), ('Meest Express', 'Meest Express')], max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
