# Generated by Django 4.1.7 on 2023-05-14 17:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_alter_delivery_office_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='office_number',
            field=models.IntegerField(blank=True, default=1, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
