# Generated by Django 4.1.7 on 2023-05-15 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_delivery_office_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_email_was_sent',
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
