# Generated by Django 4.1.7 on 2023-05-30 15:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_remove_order_is_email_was_sent_alter_order_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='office_number',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
