# Generated by Django 4.1.7 on 2023-09-21 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_alter_delivery_office_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='office_number',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
