name: OnlineShopProj CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.6-alpine
        env:
          POSTGRES_DB: ${{ secrets.DATABASE_NAME }}
          POSTGRES_USER: ${{ secrets.DATABASE_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
                 --health-cmd pg_isready
                 --health-interval 10s
                 --health-timeout 5s
                 --health-retries 5
        
      redis_db:
        image: redis:7-alpine3.16
        ports: 
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          --entrypoint bin/bash -c "redis-server /internet_shop/int_shop/config/redis/redis.conf"
        
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: |
        cd internet_shop/int_shop
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create env file
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: Run Tests
      run: |
        cd internet_shop/int_shop
        python manage.py test
