name: OnlineShop Tests

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14.6-alpine
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        volumes:
          - /var/run/postgresql:/var/run/postgresql  # volume for connection socket
        options: >-
           --health-cmd pg_isready
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5
          
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Create postgres user with createdb privilege
      run: |
        sudo docker exec ${{ job.services.postgres.id }} sh -c "psql -U postgres -p 5432 -c 'CREATE USER ${{ secrets.DATABASE_USER }} CREATEDB;'"
    - name: Run redis server in Docker with custom config file
      run: | 
        sudo docker run -v ./internet_shop/int_shop/config/redis/redis.conf:/usr/local/etc/redis/redis.conf -p 6379:6379 --name redis_db -d redis:7-alpine3.16 redis-server /usr/local/etc/redis/redis.conf
    - name: Install Dependencies
      run: |
        cd internet_shop/int_shop
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Create env file
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
        mv .env internet_shop/int_shop/int_shop/settings/.env
    - name: Run tests with Coverage
      run: |
        cd internet_shop/int_shop
        coverage run --source '.' --omit '*/migrations/*,*/tests/*,*/settings/*,int_shop/*' manage.py test
    - name: Coverage report
      run: |
        cd internet_shop/int_shop
        coverage report
